Set WshShell = WScript.CreateObject("WScript.Shell")
Set WshSysEnv = WshShell.Environment("PROCESS")
WshShell.Run("taskkill /f /im php-win.exe")
WshShell.Run("taskkill /f /im php.exe")
WshShell.Run("taskkill /f /im sqliteman.exe")
WScript.Sleep 3000  ' 3 segundos deve ser suficiente para o kill matar processos parados, e não o correto (abaixo)
WshShell.Run("php-win src\cv3\Reinicializa.php segunda_tentativa")